// Navbar.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './Navbar.css';

const Navbar = () => {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const navigate = useNavigate();

    const menuItems = [
        { label: 'Home', path: '/' },
        { label: 'About', path: '/about' },
        { label: 'Services', path: '/services' },
        { label: 'Products', path: '/products' },
        { label: 'Contact', path: '/contact' },
    ];

    const handleNavigation = (path) => {
        navigate(path);
        setIsMenuOpen(false);
    };

    const toggleMenu = () => {
        setIsMenuOpen(!isMenuOpen);
    };

    return (
        <nav className="navbar">
            <div className="navbar-container">
                <div className="navbar-logo" onClick={() => handleNavigation('/')}>
                    MyApp
                </div>
                
                <div className={`hamburger ${isMenuOpen ? 'active' : ''}`} onClick={toggleMenu}>
                    <span className="bar"></span>
                    <span className="bar"></span>
                    <span className="bar"></span>
                </div>

                <ul className={`navbar-menu ${isMenuOpen ? 'active' : ''}`}>
                    {menuItems.map((item) => (
                        <li key={item.path} className="navbar-item">
                            <button 
                                className="navbar-link"
                                onClick={() => handleNavigation(item.path)}
                            >
                                {item.label}
                            </button>
                        </li>
                    ))}
                    <li className="navbar-item">
                        <button 
                            className="navbar-link navbar-cta"
                            onClick={() => handleNavigation('/login')}
                        >
                            Login
                        </button>
                    </li>
                </ul>
            </div>
        </nav>
    );
};

export default Navbar;

// Navbar.vue
<template>
    <nav class="navbar">
        <div class="navbar-container">
            <router-link to="/" class="navbar-logo">MyApp</router-link>
            
            <div 
                :class="['hamburger', { active: isMenuOpen }]"
                @click="toggleMenu"
            >
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>

            <ul :class="['navbar-menu', { active: isMenuOpen }]">
                <li v-for="item in menuItems" :key="item.path" class="navbar-item">
                    <router-link 
                        :to="item.path"
                        class="navbar-link"
                        @click="isMenuOpen = false"
                    >
                        {{ item.label }}
                    </router-link>
                </li>
                <li class="navbar-item">
                    <router-link 
                        to="/login"
                        class="navbar-link navbar-cta"
                        @click="isMenuOpen = false"
                    >
                        Login
                    </router-link>
                </li>
            </ul>
        </div>
    </nav>
</template>

<script>
export default {
    name: 'Navbar',
    data() {
        return {
            isMenuOpen: false,
            menuItems: [
                { label: 'Home', path: '/' },
                { label: 'About', path: '/about' },
                { label: 'Services', path: '/services' },
                { label: 'Products', path: '/products' },
                { label: 'Contact', path: '/contact' },
            ]
        };
    },
    methods: {
        toggleMenu() {
            this.isMenuOpen = !this.isMenuOpen;
        }
    }
};
</script>

<style scoped>
/* Use the CSS from style.css above */
</style>
